# .streamlit/secrets.toml

[snowcat]
user = "rblum"
password = "SnowRB01!"
account = "snowcat2.preprod5.us-west-2.aws"
warehouse = "app_wh"
database = "dcr_demo_provider_db"
schema = "public"
role = "accountadmin"

[snowcat2]
user = "rblum"
password = "SnowRB01!"
account = "snowcat.preprod5.us-west-2.aws"
warehouse = "app_wh"
database = "dcr_demo_app"
schema = "public"
role = "accountadmin"
